elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "127.0.0.1:9200:9200"
    - "127.0.0.1:9300:9300"
  volumes:
    - /data/storage:/usr/share/elasticsearch/data
logstash:
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - /data/log:/data/log
  ports:
    - "127.0.0.1:5000:5000"
    - "127.0.0.1:5044:5044"
  links:
    - elasticsearch
  environment:
    - LS_HEAP_SIZE=2048m
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "127.0.0.1:5601:5601"
  links:
    - elasticsearch
