#!/bin/bash
docker stop dockerelk_kibana_1 dockerelk_logstash_1 dockerelk_elasticsearch_1
docker rm dockerelk_kibana_1 dockerelk_logstash_1 dockerelk_elasticsearch_1
docker rmi dockerelk_logstash
docker-compose up -d
